stages:
    - test
    - build
    - deploy

.test website:
    image: node:16-alpine
    stage: test
    script:
        - yarn install
        - yarn test

build website:
    image: node:16-alpine
    stage: build
    script:
        - yarn install
        - yarn build
    artifacts:
        paths:
            - build/

netlify:
    stage: deploy
    image: node:16-alpine
    script:
        - npm install -g netlify-cli
        - if [ "$CI_COMMIT_BRANCH" == "develop" ]; then netlify deploy --site=c057be07-f542-4864-82ec-a168d1f7e211 --dir=build --prod; else netlify deploy --dir=build --prod; fi
